## 도커로 MySQL 킴 

services:
  mysql:
    image: mysql:8.0
    container_name: sis-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stock_issue_scanner
      MYSQL_USER: sis_user
      MYSQL_PASSWORD: sis_password
      TZ: Asia/Seoul
    ports:
    # 3306 충돌나서 바꿈 
      - "3307:3306"  # 내 컴퓨터 3307 에서 컨테이너 안의 3306의 mysql 연결 
    volumes: 
    # volumes ? 컨테이너 안의 mysql 데이터 폴더를 컨테이너 밖의 내 컴터에저장 
      - sis_mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  sis_mysql_data: